### ISSUE TITLE
Allow creation of GitHub Discussions

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/AppConfiguration-Announcements#21]
Allow creation of GitHub Discussions so that the community can discuss issues such as #20, instead of using issues.

**Comment by zhenlan** [comment]
@tomkerkhove, this repo is for team announcements _only_. As noted in the [README](https://github.com/Azure/AppConfiguration-Announcements/blob/main/README.md) of this repo as well as in #20, please open issues in [Azure/AppConfiguration repo ](https://github.com/Azure/AppConfiguration) to report issues or share feedback.

(This issue will be closed and locked.)
